version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:15.1
    ports:
      - "5431:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    container_name: pgAdminWebApp
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=supersecret
      - PGADMIN_DEFAULT_EMAIL=dbarrientos@google.com
volumes:
   postgres-db: